### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by alireza-f** [DaveNugent/TwitterMostUsedWord#1]
It shows this error, can you help me?

Getting data for jack
Traceback (most recent call last):
  File "C:\Users\jack\Documents\GitHub\TwitterMostUsedWord\TwitterMostUsedWord\TwitterMostUsedWord.py", line 24, in <module>
    item = api.get_user(userName)
  File "C:\Users\jack\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\tweepy\binder.py", line 250, in _call
    return method.execute()
  File "C:\Users\jack\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\tweepy\binder.py", line 233, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 89, 'message': 'Invalid or expired token.'}]
[Finished in 6.03s]

**Comment by DaveNugent** [comment]
Sorry I probably should have written a README for this. Did you replace the xs on lines 10 - 13 of TwitterMostUsedWord.py with your own credentials?

CONSUMER_KEY = "xxxxxxxxxxxx"
CONSUMER_SECRET = "xxxxxxxxxxxx"
ACCESS_TOKEN = "xxxxxxxxxxxx-xxxxxxxxxxxx"
ACCESS_TOKEN_SECRET = "xxxxxxxxxxxx"

**Comment by alireza-f** [comment]
Yep, I didn't know that and entered them but there is a new problem that i can't understant. sorry for questioning frequently, i am new in python.

Traceback (most recent call last):
  File "C:\Users\jack\Documents\GitHub\TwitterMostUsedWord\TwitterMostUsedWord\TwitterMostUsedWord.py", line 41, in <module>
    maskArray = npy.array(Image.open("cloud.png"))
  File "C:\Users\alire\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\PIL\Image.py", line 2809, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'cloud.png'
